import ProductDropzone from "@/components/ProductDropzone"
import Toolbox from "@/components/Toolbox"
import { CloudinaryProvider } from "@/context/cloudinary"
import { ToolboxProvider } from "@/context/toolbox"
import Head from "next/head"

export default function Home() {
  return (
    <CloudinaryProvider>
      <ToolboxProvider>
        <Head>
          <title>Postify</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="max-w-7xl m-auto grid grid-cols-1 w-full h-screen p-4">
          <header className="flex justify-center py-4 flex-col items-center text-white gap-y-2">
            <h1 className="text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-green-300 via-blue-500 to-purple-600">
              Postify
            </h1>
            <h3 className="text-2xl">
              Upload the photo of your product and generate the sale publication
              for your Social Networks
            </h3>
          </header>

          <main className="w-full block">
            <section className="h-full max-h-[600px] flex">
              <div className="w-3/4 flex items-center justify-center p-4 bg-white rounded-tl-xl rounded-bl-xl">
                <ProductDropzone />
              </div>

              <div className="w-1/4 bg-white p-4 flex rounded-tr-xl rounded-br-xl flex-col gap-y-4 overflow-auto border border-l-gray-100">
                <Toolbox />
              </div>
            </section>
          </main>

          <footer className="flex justify-center items-center pt-4  gap-x-2 font-semibold text-white/50">
            Made with{" "}
            <a
              href="https://nextjs.org/"
              target="_blank"
              rel="noreferrer"
              className="hover:text-white"
            >
              Nextjs
            </a>{" "}
            &
            <a
              href="https://cloudinary.com"
              target="_blank"
              rel="noreferrer"
              className="hover:text-white"
            >
              Cloudinary
            </a>
          </footer>
        </div>
      </ToolboxProvider>
    </CloudinaryProvider>
  )
}
