import ProductDropzone from "@/components/ProductDropzone"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Postify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl m-auto grid grid-cols-1 w-full h-screen p-4">
        <header className="flex justify-center py-4">
          <h1 className="text-6xl font-bold text-white">Postify</h1>
        </header>

        <main className="w-full block">
          <section className="h-full flex">
            <div className="w-3/4 flex items-center justify-center p-4 bg-gray-200/80 rounded-tl-xl rounded-bl-xl">
              {/* <img
                src="https://www.socialpilot.co/wp-content/uploads/2021/07/Facebookpersonalprofileimagesize-1.jpg"
                alt="Image to process"
                width={800}
                height={600}
              /> */}
              <ProductDropzone />
            </div>

            <div className="w-1/4 bg-white p-4 flex rounded-tr-xl rounded-br-xl flex-col gap-y-4">
              <button className="relative inline-flex items-center justify-center p-0.5 w-full overflow-hidden text-lg font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:ring-4 focus:outline-none focus:ring-white hover:scale-105">
                <span className="relative px-5 py-4 transition-all ease-in duration-75 w-full bg-white rounded-md group-hover:bg-opacity-0 text-blue-800 hover:text-white">
                  GENERATE
                </span>
              </button>

              <div className="flex flex-col">
                <label
                  htmlFor="target"
                  className="block mb-2 text-lg font-medium text-gray-900"
                >
                  Target:
                </label>
                <select
                  id="target"
                  className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5"
                >
                  <option>Select your target</option>
                  <option>Facebook</option>
                  <option>Instagram</option>
                  <option>Twitter</option>
                  <option>Youtube</option>
                  <option>Pinterest</option>
                </select>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="name"
                  className="block mb-2 text-lg font-medium text-gray-900"
                >
                  Product Name:
                </label>
                <input
                  type="text"
                  id="name"
                  placeholder="Adidas shoes..."
                  className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full py-2 px-4"
                />
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="price"
                  className="block mb-2 text-lg font-medium text-gray-900"
                >
                  Price:
                </label>
                <input
                  type="text"
                  id="price"
                  placeholder="0.00"
                  className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full py-2 px-4"
                />
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="sizes"
                  className="block mb-2 text-lg font-medium text-gray-900"
                >
                  Sizes:
                </label>
                <div className="grid grid-cols-4">
                  <span className="flex items-center">
                    <input
                      id="size_0"
                      type="checkbox"
                      value="0"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_0"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      0M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_3"
                      type="checkbox"
                      value="3"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_3"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      3M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_6"
                      type="checkbox"
                      value="6"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_6"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      6M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_9"
                      type="checkbox"
                      value="9"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_9"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      9M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_12"
                      type="checkbox"
                      value="12"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_12"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      12M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_18"
                      type="checkbox"
                      value="18"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_18"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      18M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_24"
                      type="checkbox"
                      value="24"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_24"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      24M
                    </label>
                  </span>

                  <span className="flex items-center">
                    <input
                      id="size_t2"
                      type="checkbox"
                      value="t2"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <label
                      htmlFor="size_t2"
                      className="ml-2 text-sm font-medium text-gray-900"
                    >
                      T2
                    </label>
                  </span>
                </div>
              </div>

              <div className="flex flex-col">
                <label
                  htmlFor="description"
                  className="block mb-2 text-lg font-medium text-gray-900"
                >
                  Description:
                </label>
                <textarea
                  id="description"
                  rows="4"
                  placeholder="Some description..."
                  className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 resize-none"
                ></textarea>
              </div>
            </div>
          </section>
        </main>

        <footer className="flex justify-center items-center pt-4  gap-x-2 font-semibold text-white/50">
          Made with{" "}
          <a href="https://cloudinary.com" target="_blank" rel="noreferrer">
            Cloudinary
          </a>
        </footer>
      </div>
    </>
  )
}
